name: tractian_fragmentable
packages:
  - packages/**

scripts:
  get:
    exec: fvm flutter pub get
    description: run pub get in all packages

  test:
    exec: fvm dart test
    description: run tests in all packages
    packageFilters:
      dirExists: "test"
      flutter: true

  build_dart:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      flutter: true
