name: fragmentable_generator_example
description: >-
  Example project for the fragmentable_generator package.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  fragmentable_annotation:
    path: ../../fragmentable_annotation

dev_dependencies:
  fragmentable_generator:
    path: ../../fragmentable_generator
  build_runner: 2.4.15
