name: fragmentable_annotation
description: >-
  Classes and helper functions that support Fragmentable code generation via the
  `tractian_fragmentable` package.
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  meta: 1.16.0

resolution: workspace
